Added git configuration in devboxes

diff --git a/devbox b/devbox
--- a/devbox
+++ b/devbox
@@ -3,7 +3,8 @@
 if [[ $1 == "create" ]]; then
     XAUTH=$HOME/.Xauthority
     touch $XAUTH
-    docker run -itd --network=host --env DISPLAY=$DISPLAY -v /spare:/spare -v $XAUTH:/root/.Xauthority --name=$2 devbox /bin/bash &>/dev/null && echo "$2 has been successfully created" || echo "$2 could not be created"
+    touch $HOME/.gitconfig
+    docker run -itd --network=host --env DISPLAY=$DISPLAY -v /spare:/spare -v $XAUTH:/root/.Xauthority -v $HOME/.gitconfig:/root/.gitconfig -v $HOME/.ssh:/root/.ssh --name=$2 devbox /bin/bash &>/dev/null && echo "$2 has been successfully created" || echo "$2 could not be created"
 elif [[ $1 == "stop" ]]; then
     docker stop $2 &>/dev/null && echo "$2 has been stopped" || echo "$2 could not be stopped"
 elif [[ $1 == "start" ]]; then
@@ -15,7 +16,7 @@ elif [[ $1 == "rm" ]]; then
 elif [[ $1 == "attach" ]]; then
     docker exec -it $2 /bin/bash
 elif [[ $1 == "list" ]]; then
-    docker ps --filter ancestor=devbox --format "table {{.Names}}\t{{.ID}}\t{{.Status}}\t{{.Size}}" -a
+    docker ps --filter ancestor=devbox --format "table {{.Names}}\t{{.Status}}\t{{.Size}}" -a
 elif [[ $1 == "install" ]]; then
     docker pull rajatjain1997/devbox
 elif [[ $1 == "cp" ]]; then
